const Features = [{
  id:0,
  name:"angleofbc",
  label:"重心夹角",
  desc:"重心-脖子-臀"
},{
  id:1,
  name:"oriofupper",
  label:"上肢朝向",
  desc:""
},{
  id:2,
  name:"orioflower",
  label:"下肢朝向",
  desc:""
},{
  id:3,
  name:"oriofbody",
  label:"左右朝向",
  desc:""
},{
  id:4,
  name:"angleofuppershoulder",
  label:"上肩夹角",
  desc:"鼻子-脖子-左肩"
},{
  id:5,
  name:"angleoflowershoulder",
  label:"下肩夹角",
  desc:"臀-脖子-左肩"
},{
  id:6,
  name:"angleofleftshoulder",
  label:"左肩夹角",
  desc:"脖子-左肩-左肘"
},{
  id:7,
  name:"angleofrightshoulder",
  label:"右肩夹角",
  desc:"脖子-右肩-右肘"
},{
  id:8,
  name:"angleofleftelbow",
  label:"左肘夹角",
  desc:"左肩-左肘-左腕"
},{
  id:9,
  name:"angleofrightelbow",
  label:"右肘夹角",
  desc:"左肩-左肘-左腕"
},{
  id:10,
  name:"angleofhip",
  label:"臀部夹角",
  desc:"脖子-臀-左臀"
},{
  id:11,
  name:"angleoflefthip",
  label:"左臀夹角",
  desc:"臀-左臀-左膝"
},{
  id:12,
  name:"angleofrighthip",
  label:"右臀夹角",
  desc:"臀-右臀-右膝"
},{
  id:13,
  name:"angleofleftknee",
  label:"左膝夹角",
  desc:"左臀-左膝-左踝"
},{
  id:14,
  name:"angleofrightknee",
  label:"右膝夹角",
  desc:"右臀-右膝-右踝"
},{
  id:15,
  name:"angleofleftankle",
  label:"左踝夹角",
  desc:"左膝-左踝-左脚趾"
},{
  id:16,
  name:"angleofrightankle",
  label:"右踝夹角",
  desc:"右膝-右踝-右脚趾"
},{
  id:17,
  name:"angleofleftshouldersection",
  label:"左臂区夹角",
  desc:""
},{
  id:18,
  name:"angleofrightshouldersection",
  label:"右臂区夹角",
  desc:""
},{
  id:19,
  name:"angleoflefthipsection",
  label:"16左臀区夹角",
  desc:""
},{
  id:20,
  name:"angleofrighthipsection",
  label:"右臀区夹角",
  desc:""
}]

module.exports=Features;